# Generated by Django 3.1.4 on 2020-12-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_fav'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fav',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=int, editable=False, primary_key=True, serialize=False),
        ),
    ]
